#!/bin/python3

import sys


def fibonacci_digit_list(n):
    fibionacci = [0] * 500000
    ndigit = [0] * 5001
    fibionacci[1] = 1
    fibionacci[2] = 1
    ndigit[0] = 0
    ndigit[1] = 1
    nth = 3
    last_digit = 1
    
    while True:
        fibionacci[nth] =fibionacci[nth -1 ] + fibionacci[nth -2]
        dig_current = len(str(fibionacci[nth])) 
        if dig_current != last_digit:
            ndigit[dig_current] = nth
            # print(dig_current, nth)
            if dig_current >= n:
                return ndigit
        last_digit = dig_current
        nth += 1


Ndigitx = fibonacci_digit_list(5000)
t = int(input().strip())
for a0 in range(t):
    n = int(input().strip())
    print(Ndigitx[n])